version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: nginx/
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    # expose: 
    #   - "80"
    #   - "443"
  drawerio-frontend:
    container_name: drawerio-frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
    image: drawerio-frontend
    env_file:
      - frontend/.env
    depends_on:
      - drawerio-app
    ports:
      - "3000:3000"
    # expose: 
    #   - "3000"
  drawerio-api:
    container_name: drawerio-api
    build:
      context: backend-express/
      dockerfile: Dockerfile
    image: drawerio-api
    env_file:
      - backend-express/.env
    depends_on:
      - db
    ports:
      - "5000:5000"
    expose: 
      - "5000"
  db:
    container_name: postgres
    image: postgres:latest
    env_file:
      - backend-express/.env
    ports:
      - "5432:5432"
    depends_on:
      - nginx
    # expose:
    #   - "5432"
    restart: always
    volumes: 
      - ./backend-express/initdb.sql:/docker-entrypoint-initdb.d/create_tables.sql
